version: "3.9"

services:
  nginx:
    volumes:
      - ./services/nginx/etc/default.conf:/etc/nginx/templates/default.conf.template
    links:
      - node

  php:
    environment:
      ENV: production

  node:
    build: ./services/node
    ports:
      - "5000:5000"

  mysql:
    restart: always
